dist: trusty
language: python
git:
  depth: 5
addons:
  postgresql: 9.6
  firefox: latest-esr
before_install:
 - git branch -vv | grep '^*'
 - pwd
 - find . -name "*.sh" -exec bash -n {} \;

 # Temporarily install 9.6.2 manually, remove once 9.6.2 is default on Travis

 - sudo add-apt-repository "deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main"
 - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
 - sudo apt-get update
 - sudo apt-get install postgresql-9.6

 # For ttw tests
 - wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
 - mkdir -p geckodriver
 - tar -xzf geckodriver-v0.15.0-linux64.tar.gz -C geckodriver
 - export PATH="geckodriver:$PATH"
 - geckodriver --version
 - firefox --version
cache:
  directories:
    - env/bin
    - env/lib/python2.7/site-packages
    - geckodriver
install:
 - if [ "${TRAVIS_BRANCH}" = "master" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then rm -rf env; fi
 - touch requirements.txt package.json
 - make env -j2
before_script:
 - echo "DATABASE_URL=dbname=gratipay" | tee -a tests/local.env local.env

 # Turn off all cron threads.
 - echo "UPDATE_CTA_EVERY=0" >> local.env
 - echo "CHECK_DB_EVERY=0" >> local.env
 - echo "CHECK_NPM_SYNC_EVERY=0" >> local.env
 - echo "EMAIL_QUEUE_FLUSH_EVERY=0" >> local.env
 - echo "EMAIL_QUEUE_LOG_METRICS_EVERY=0" >> local.env

 - psql -U postgres -c 'CREATE DATABASE "gratipay";'
 - if [ "${TRAVIS_BRANCH}" = "master" -a "${TRAVIS_PULL_REQUEST}" = "false" ]; then
     rm -rfv tests/py/fixtures;
     echo "LOAD_BRAINTREE_FORM_ON_HOMEPAGE=yes" >> local.env;
   fi
script: LD_LIBRARY_PATH=/usr/local/lib xvfb-run make test-schema bgrun test doc
notifications:
  email: false
  irc: false
